### ISSUE TITLE
Extension moves valid bookmarks to trash

### ISSUE THREAD

**Issue by raggleton** [samueldobbie/remarkable#1]
Using version 1.0.0 with Chrome 98.0.4758.102. The extension has moved bookmarks with valid URLS to trash, e.g. https://www.gimmesomeoven.com/chocolate-chip-cookies/, or http://thepeteplan.wordpress.com/

**Comment by samueldobbie** [comment]
Thanks for reporting (and for the cookie recipe) @raggleton!

I'll look into this soon.

**Comment by raggleton** [comment]
Just FYI for anyone who experiences the same thing, Chrome keeps a backup copy of your bookmarks, so it's possible to restore them: https://www.reddit.com/r/chrome/comments/9r18dj/comment/e8ean9b/

**Comment by samueldobbie** [comment]
To add to that, the extension is non-destructive, so your bookmarks will never be deleted, they'll just be moved to a bookmark folder called `Trash`.
